sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "3De1z6JZeWQTLvgsAgazGRlLRh6qMwMskmNvRCzpDuvyPsh0ElVcBcSAxsPdYUFZH1dodtlN90e7xIA0ZOhqrJtJCKJdCjLibO2lCLmsxsER37LIfImkg1lf41yM34+wg9yTwZEBU83xeG4AlafunM5X47xHw5m5OIHkFhFgpXCs2q5nHxCIgvgkoBzzJdvAIl9vddvdIEWSwug266pkrR2CCpsOPxMusZsGJ48qfktpxz56ylCDLamlCNxPrFPDDFhADyclJtYt7MLodc3uYFqS//e+3gX2sjPovB8gs/lBv6XIHDqJGn3r+BAEvtK+PjNiCPkIdQjwg/c16+2lY6DNwyOt4Ft3YMeZm/ttA0rpcZ9rZhF7u2RBNpFpfW1oH41xFMA8KKriDqouFMoLI4wndbytFwVmRjBJIbRuwGkHnPUKBT4hLdXtbRkghDmJNoH7mNYdSXlEXzIGfL2jlUyt3a6k/HMQzQnxmzo50EIAKWAGv/DB4aqPwIt64ZahdH+6ZPPW7I+eUad9E4952Nta/0X5ANQbG/2D+nbYZS53V2iiWD8lqsf1aX5yTdljZcESdT9FmR744NjM103neejP3aqcbY8pvdhJ7aLcY4si7W/1Zs75QVnqaE5zmzL5GkqxjqCt0DRsE1DEVPSoODy9lTByv6H57lUjlJvnzN8="
branches:
  only:
    - master
