# Jekyll configuration
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
exclude: [vendor]
highlighter: rouge
paginate_path: "/page-:num/"
permalink: /:title
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: "<!--more-->"
# Number of posts on each page.
paginate: 20
language: 'en-uk'
# language attribute in <html> element.
lang: en
words_per_minute: 100
CNAME: terribletester.com

title: terribletester
description:
  meta: Learnings of a Terrible Tester.
  subtitle: Learnings of a Terrible Tester. <a href="https://github.com/sitture">&lt;/&gt; on Github</a>.
author:
  name: Haroon Sheikh
  email: haroon_sheikh@hotmail.co.uk
  # Optional text (html) to display after author name. Leave empty if you don't want it.
  info: (@<a href="https://twitter.com/mrhsheikh">mrhsheikh</a>)

url: https://terribletester.com
baseurl: "/"

# FROM THIS POINT ON EVERYTHING IS OPTIONAL

##############
# APPEREANCE #
##############

# If you want to show the subtitle anywhere else than the front page, use
# {% include subtitle.html %} to include it anywhere you want.
show-subtitle: true
display-social-icons: true
# If you want social links to open in a new tab, set this as true
social-icons-open-newtab: true

footer-text: Learning of a Terrible Tester

# Preferably 64px in height. Leave empty = disable.
logo-image: # /terribletester-lon.png

# Toolbar color for Chrome on Android.
theme-color-attr: "#00f0ff"

# Color of Microsoft live Tile.
ms-tile-color: "#00f0ff"

# Color used throughout the theme. Format: R, G, B.
theme-color: 0, 240, 255 # Original: 0, 240, 255

# Text color used throughout the theme. Format: R, G, B.
text-color: 0, 0, 0 # Original: 0, 0, 0

# Background color used throughout the theme. Format: R, G, B.
# Note: if you change the background color AND you use cover images, you should
#       also change the CSS gradient in "_includes\gradient.css" to match the
#       background color. Edit and copy it from here:
#       http://www.colorzilla.com/gradient-editor/#ffffff+0,ffffff+100&0+0,1+100
background-color: 255, 255, 255 # Original: 255, 255, 255

display-author-post-page: true
display-author-front-page: true

# http://alanwsmith.com/jekyll-liquid-date-formatting-examples
date_format: "%b %-d, %Y"

# Minimal screen-width after which the navigation will change position from
# vertical to horizontal.
nav-breaking-point: 520px

# Display links for the previous and next post on post pages.
display-next-prev-post: false

# Leave empty if you don't want comments on post pages.
disqus-shortname: terribletester


################
# SOCIAL ICONS #
################

# Use a complete url here, including http:// and such. Requiring just usernames
# has been considered, but this is way more customizable.
twitter: https://twitter.com/mrhsheikh
youtube:
instagram:
tumblr:
facebook:
google-plus:
reddit:
soundcloud:
medium:
linkedin:
github: https://github.com/haroon-sheikh
behance:
codepen:
dribbble:
trello:
stack-overflow:
bitcoin:
paypal:


#####################
# CUSTOMIZABLE TEXT #
#####################

# Useful for translating into other languages.

var_on_the_web: On the web
var_read: Read # Text after each post summary on the homepage.
var_newer: Newer
var_older: Older
var_next_post: Next post
var_previous_post: Previous post
var_less_than_a_minute_read: Less than a minute read
var_min_read: min read # Text after reading time. Example: 5 min read.
var_post_by: Post by
var_guest_post_by: Guest post by
var_your_email: Your email
var_your_message: Your message


# Google Analytics
google_analytics: UA-142314788-1

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
lsi: False
username: sitture
repo: terribletester
branch: master
relative_source: ../terribletester
destination: gh-pages
production_url:  https://terribletester.com/
source_url:  https://github.com/sitture/terribletester/
